name: Deploy to AWS Amplify

on:
  push:
    branches:
      - main  # Trigger the workflow on push events to the main branch; change as needed
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest  # The type of runner that the job will run on

    steps:
    - uses: actions/checkout@v2  # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

    - name: Initialize AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Replace <your-aws-region> with your AWS region, e.g., us-east-1

    - name: Deploy to AWS Amplify
      uses: aws-actions/amplify-console-deploy-action@v1.1.2
      with:
        amplify_app_id: ${{ secrets.AMPLIFY_APP_ID }}  # The app ID of your Amplify app
        amplify_env_name: dev  # The name of your Amplify environment, e.g., 'prod' or 'dev'
        head_ref: ${{ github.ref }}  # The branch to deploy
